### ISSUE TITLE
哥们QQ 多少啊.加个好友啊.

### ISSUE THREAD

**Issue by pslxx** [bingo-oss/bui-weex-sample#1]
哥们QQ 多少啊.加个好友啊 正在整bui-weex

**Comment by tonyyls** [comment]
抱歉，暂时不方便提供联系方式。 bui-weex在月底会提供公测版本。 到时候会配套工具，官网，文档等资源。你目前所看到的 只是我们做的开发示例。感谢关注！

**Comment by pslxx** [comment]
私人交个朋友没关系吧...都是搞这一块的..我们有自己集成开发的模块组件

比如 视频 富文本 导航 地图 事件交互 支付 分享 等,,可以一起交流交流

**Comment by tonyyls** [comment]
570519827
